### ISSUE TITLE
CUDA error and Libomptarget error: openmp-offload method

### ISSUE THREAD

**Issue by tmh97** [ANL-CESAR/RSBench#15]
Simulation crashes at runtime for openmp-offload mode:

Compiler: LLVM 14.0.0 (nightly build: February 2nd 2022) + cudatoolkit/21.9_11.4
Machine: Perlmutter (NVIDIA A100 GPU + AMD Milan CPU)

Reproducer
1. cd openmp-offload
2. export CC=clang
3. make
4. ./rsbench -m event

No changes were made to the Makefile

`Beginning baseline event based simulation on device...
CUDA error: an illegal memory access was encountered 
Libomptarget error: Copying data from device failed.
Libomptarget error: Call to targetDataEnd failed, abort target.
Libomptarget error: Failed to process data after launching the kernel.
Libomptarget error: Run with LIBOMPTARGET_INFO=4 to dump host-target pointer mappings.
simulation.c:24:2: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
Aborted
`

**Comment by jtramm** [comment]
Thanks for reporting this! I am able to reproduce the error with the nightly build of LLVM as well.

I also tested with a few other compilers and systems. It is running cleanly when compiled with NVHPC for A100, AOMP for MI100, and OneAPI for Gen9.

I also ran the LLVM compiled version through `cuda-gdb` and the error seems hard to pin down. At first it says the error is coming from the Clang CUDA math library:

```
thread 1 "rsbench" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 1, block (122,0,0), thread (0,0,0), device 0, sm 15, warp 0, lane 0]
0x000000000114ecc0 in sin[device={arch(nvptx, nvptx64)}, implementation={extension(match_any)}] () at /gpfs/jlse-fs0/users/jtramm/compilers/physor_2022_version/llvm-install/lib/clang/14.0.0/include/__clang_cuda_math.h:293
293	__DEVICE__ double sin(double __a) { return __nv_sin(__a); }
(cuda-gdb) bt
#0  0x000000000114ecc0 in sin[device={arch(nvptx, nvptx64)}, implementation={extension(match_any)}] () at /gpfs/jlse-fs0/users/jtramm/compilers/physor_2022_version/llvm-install/lib/clang/14.0.0/include/__clang_cuda_math.h:293
#1  calculate_sig_T () at /gpfs/jlse-fs0/users/jtramm/compilers/physor_2022_version/llvm-install/lib/clang/14.0.0/include/__clang_cuda_math.h:293
#2  0x000000000111c6d0 in calculate_micro_xs_doppler () at simulation.c:195
#3  0x00000000011173a0 in calculate_macro_xs () at simulation.c:105
#4  0x0000000000f8a420 in __omp_outlined__1 ()
#5  0x00000000010c9110 in (anonymous namespace)::invokeMicrotask(int, int, void*, void**, long) ()
#6  0x00000000010ebcc0 in __kmpc_parallel_51 ()
#7  0x00000000010e6250 in __omp_outlined__ ()
#8  0x00000000010f8bb0 in __omp_offloading_31_7464625b_run_event_based_simulation_l24<<<(79688,1,1),(128,1,1)>>> () at simulation.c:24
```

But then when the call to `sin()` is removed the error moves somewhere else, and when I remove that function entirely the error moves to an another different place. My guess is that this is likely to be a LLVM-specific compiler error of some sort, given that it's running correctly with the NVIDIA, AMD, and Intel compilers. If you have reason to believe though that this is indeed an application error, please don't hesitate to reopen the issue!

**Comment by ggeorgakoudis** [comment]
FYI compiling with O3 and upstream Clang/LLVM works

**Comment by jdoerfert** [comment]
> FYI compiling with O3 and upstream Clang/LLVM works

To elaborate, the stack trace above shows various functions that should have been inlined. I suspect it was compiled at O0 (=default when no -O is given). While O0 is nice for "debugging" it is not nice when it comes to resources. Key optimizations have to happen to avoid us draining heap memory (among other things). I would recommend O1 or higher for any offload build, even if that makes "debugging" harder.

**Comment by jtramm** [comment]
Thanks @jdoerfert -- this is a good observation. In RSBench OpenMP version we have an OPTIMIZE option in the makefile but it has no effect. I just pushed a change to ensure that -O3 is included when the flag is enabled.
