### ISSUE TITLE
Result of computation is never checked -> optimising compilers skew results

### ISSUE THREAD

**Issue by stephand** [ANL-CESAR/RSBench#4]
Again, similar to XSbench issue:
in main.c:
calculate_macro_xs( macro_xs, mat, E, input, data, sigTfactors, &abrarov, &alls ); 
The results in macro_xs are never checked.  Simply adding asm volatile (""::"m"(macro_xs[0]),...) brings performance back in line for aggressive optimising compilers (adding LTO to GCC optimisation flags).
Three core difference is significant again:
$ while true; do res1=$(./rsbench -s small | awk '/Lookups.s:/ {print $2}'); res2=$(./rsbench.force_use -s small | awk '/Lookups.s:/ {print $2}'); echo $res1 $res2; done
808,197 401,135
792,076 367,372
765,152 366,358
Showing a performance difference of 2x.

So please make sure that the benchmark results get used, either by employing similar asm volatile barriers, or adding a running sum over the results (and printing / asm-volatile-consuming that).

**Comment by jtramm** [comment]
Thanks for notifying us of this!

I'm able to reproduce the issue when the -flto flag was used for linker time optimization. I've added in a copy to the heap in order to ensure that the code behaves as expected when the -flto flag is used.

Note that this issue did not affect the behavior of the code under normal compilation, it only occured with -flto.

Thanks!

**Comment by stephand** [comment]
Thanks for fixing.  I do not find  the solution with the memcpy particularly elegant.  My proposal with the asm volatile (that can be mapped into a "consume" macro) would avoid the copy, but is also a bit of a hack.  Having a very clean running sum of the results might overserialise the parallel execution.

Is there some architectural guarantee that the compiler does not trace through the memcpy and optimise that away when the other part is never used either?

In either case, this seems to work for now, so thanks for fixing.
