### ISSUE TITLE
Possible buffer overrun of poles buffer

### ISSUE THREAD

**Issue by ilan-t** [ANL-CESAR/RSBench#5]
This line

https://github.com/ANL-CESAR/RSBench/blob/cf42d27d39bd520af4c87ad9de35f3f8f4fad3bc/src/init.c#L57

... assumes that the total equals to avg*nuclides.
But that is only true if we never hit this line:

https://github.com/ANL-CESAR/RSBench/blob/cf42d27d39bd520af4c87ad9de35f3f8f4fad3bc/src/init.c#L16

If we do, then the total is larger, and RSBench reaches a buffer overrun bug.
This is a marginal case and highly unlikely with large avg_n_poles, but still a problem with lower values.

This can be fixed locally, by summing up `n_poles` inside `generate_poles` instead of multiplying by the average.
Not sure if there are other side effects to this, though

**Comment by jtramm** [comment]
Yes, definitely looks like a bug -- thanks for pointing this out! I'm actually planning on updating RSBench with a number of other features (namely, accelerator versions in CUDA, OpenCL, etc) sometime in the next few weeks, so will plan on including a fix at that point. Thanks again!
